In [1]:
import pandas as pd
bond = pd.read_csv("Bond.csv")

bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [2]:
bond.set_index("Year", inplace = True)
bond.head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

In [3]:
bond.sort_values("Actor")

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
2015,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN
2008,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
2006,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2012,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
1969,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
2002,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
1999,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
1997,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
1995,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
1985,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
1983,Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
1981,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
1977,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
1974,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
1973,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
1979,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
1983,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
1971,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
1967,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1987,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
1989,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9

In [9]:
bond["Bond Actor Salary"].fillna(value = bond["Bond Actor Salary"].mean(), inplace =True)

In [10]:
bond["Bond Actor Salary rank"] =bond["Bond Actor Salary"].rank(ascending = True)

In [11]:
bond.head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary,Bond Actor Salary rank
Year,,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.60,1.5
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.60,3.0
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.20,4.0
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.70,7.0
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,6.85,14.5

In [17]:
bond.sort_values("Bond Actor Salary rank", ascending = False, inplace = True)
bond

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary,Bond Actor Salary rank
Year,,,,,,,
2002,Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.90,26.0
2012,Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.50,25.0
1999,The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.50,24.0
1997,Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.00,23.0
1985,A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.10,22.0
2008,Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.10,21.0
1989,Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.90,20.0
1983,Octopussy,Roger Moore,John Glen,373.8,53.9,7.80,19.0
1981,For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,6.85,14.5
1977,The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,6.85,14.5
1974,The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,6.85,14.5
1983,Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,6.85,14.5
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,6.85,14.5
1979,Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,6.85,14.5
2015,Spectre,Daniel Craig,Sam Mendes,726.7,206.3,6.85,14.5
1973,Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,6.85,14.5
1971,Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.80,10.0
1987,The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.20,9.0
1995,GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.10,8.0
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.70,7.0
1967,You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.40,6.0
2006,Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.30,5.0
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.20,4.0
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.60,3.0
1969,On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.60,1.5
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.60,1.5